[openai]
api_key = "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"  # Replace with your actual key
